application: mijneerstewebsite-142012
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /website.php
  script: website.php
  
- url: /admin.php
  script: admin.php
  
- url: /nonadmin.php
  script: nonadmin.php  
  
- url: .*
  script: login.php
